import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next App With Material-UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body>
        {children}
      </body>
    </html>
  );
}
